
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./app/:/usr/src/app
    ports:
      - "5432:5432"
    env_file:
      - .env

  fastapi-app:
    build: ./app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./app/:/usr/src/app
      - ./logs:/app/logs
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.tgbot
    command: python3 tgbot.py
    environment:
      API_TOKEN: "${API_TOKEN}"
      FASTAPI_URL: "${FASTAPI_URL}"
    depends_on:
      - fastapi-app
    env_file:
      - .env

volumes:
  postgres_data:
